#!/bin/sh

# Exports
export DOTFILES=$HOME/dotfiles
export HISTFILE=$HOME/.zsh_history  # By default, zsh doesn't save history
export HISTSIZE=1000000
export SAVEHIST=1000000

source "$DOTFILES/zsh/functions.zsh"
source "$DOTFILES/zsh/aliases.zsh"
source "$DOTFILES/zsh/prompt.zsh"

# Plugins
zsh_add_plugin "marlonrichert/zsh-autocomplete"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
zsh_add_plugin "conda-incubator/conda-zsh-completion"
zsh_add_local_plugin "git-prompt"

fpath+="$DOTFILES/plugins/conda-zsh-completion"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/nick/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/nick/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/nick/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/nick/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

