#!/bin/sh

# Exports
export DOTFILES=$HOME/dotfiles
export HISTFILE=$HOME/.zsh_history  # By default, zsh doesn't save history
export HISTSIZE=1000000
export SAVEHIST=1000000

source "$DOTFILES/zsh/functions.zsh"
source "$DOTFILES/zsh/aliases.zsh"
source "$DOTFILES/zsh/prompt.zsh"

# Plugins
zsh_add_plugin "marlonrichert/zsh-autocomplete"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
